package com.gym.app.service;

import java.io.File;
import kong.unirest.HttpResponse;
import kong.unirest.JsonNode;
import kong.unirest.Unirest;
import kong.unirest.json.JSONObject;
import kong.unirest.json.JSONArray;

/**
 * Implementation of FaceRecognitionService using the Luxand.cloud API.
 * Handles HTTP requests to create subjects and recognize faces.
 */
public class LuxandFaceRecognitionService implements FaceRecognitionService {

    // IMPORTANT: USER MUST REPLACE THIS WITH THEIR ACTUAL LUXAND API TOKEN
    // Get a token from https://luxand.cloud/
    private static final String API_TOKEN = "INSERT_LUXAND_API_TOKEN_HERE";

    // Base URL for Luxand Cloud API
    private static final String BASE_URL = "https://api.luxand.cloud";

    /**
     * Checks if the API token has been set by the user.
     * 
     * @return true if the token is not null, not empty, and not the placeholder.
     */
    @Override
    public boolean isConfigured() {
        return API_TOKEN != null && !API_TOKEN.equals("INSERT_LUXAND_API_TOKEN_HERE") && !API_TOKEN.isEmpty();
    }

    /**
     * Enrolls a new person into the Luxand database.
     * 1. Creates a "Subject" with the given name.
     * 2. Uploads the photo to that Subject.
     * 
     * @param name  Name of the member.
     * @param photo Local photo file.
     * @return The unique ID (Subject ID) generated by Luxand.
     * @throws Exception If API calls fail.
     */
    @Override
    public String enrollFace(String name, File photo) throws Exception {
        if (!isConfigured())
            return "MOCK_FACE_TOKEN_" + System.currentTimeMillis();

        // 1. Create Person (Subject)
        HttpResponse<JsonNode> createResponse = Unirest.post(BASE_URL + "/subject")
                .header("token", API_TOKEN)
                .field("name", name)
                .asJson();

        if (createResponse.getStatus() != 200) {
            throw new Exception("Failed to create subject: " + createResponse.getStatusText());
        }

        // Extract the new Subject ID
        String faceId = createResponse.getBody().getObject().getString("id");

        // 2. Add Face Image to the Subject
        HttpResponse<JsonNode> addFaceResponse = Unirest.post(BASE_URL + "/subject/" + faceId)
                .header("token", API_TOKEN)
                .field("photo", photo)
                .asJson();

        if (addFaceResponse.getStatus() != 200) {
            throw new Exception("Failed to add face: " + addFaceResponse.getStatusText());
        }

        return faceId;
    }

    /**
     * Sends a photo to Luxand to recognize the person.
     * 
     * @param photo Local photo file to check.
     * @return The name of the person if recognized with >85% confidence, else null.
     * @throws Exception If API call fails.
     */
    @Override
    public String recognizeFace(File photo) throws Exception {
        if (!isConfigured())
            return null; // Or throw exception

        // Send photo to /photo/search endpoint
        HttpResponse<JsonNode> response = Unirest.post(BASE_URL + "/photo/search")
                .header("token", API_TOKEN)
                .field("photo", photo)
                .asJson();

        if (response.getStatus() != 200) {
            System.out.println("Recognition API Error: " + response.getBody());
            return null;
        }

        // Parse results
        JSONArray matches = response.getBody().getObject().getJSONArray("result");
        if (matches.length() > 0) {
            // Get the best match (first one)
            JSONObject match = matches.getJSONObject(0);
            double probability = match.getDouble("probability");

            // Validate confidence threshold
            if (probability > 0.85) {
                return match.getString("name");
            }
        }

        return null;
    }
}
